include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_use_package_imports: true
    directives_ordering: true
    avoid_print: true

    use_key_in_widget_constructors: true
    use_build_context_synchronously: true
    prefer_const_constructors: true
    sized_box_for_whitespace: true
    avoid_unnecessary_containers: true

    prefer_single_quotes: true
    require_trailing_commas: true
    sort_child_properties_last: true
    prefer_final_fields: true
    prefer_final_locals: true

formatter:
  page_width: 120
  trailing_commas: preserve
